version: "2"

services:
  zookeeper:
    container_name: zookeeper
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "${ZOOKEEPER_PORT}:2181"
      - "8080:8080"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka:3
    ports:
      - "${KAFKA_PORT}:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_INTER_BROKER_USER=${KAFKA_INTER_BROKER_USER}
      - KAFKA_INTER_BROKER_PASSWORD=${KAFKA_INTER_BROKER_USER}
      - KAFKA_CLIENT_USERS=${KAFKA_INTER_BROKER_USER}
      - KAFKA_CLIENT_PASSWORDS=${KAFKA_INTER_BROKER_USER}
      - KAFKA_CREATE_TOPICS="${KAFKA_CREATE_TOPICS}:${KAFKA_TOPIC_PARTITION}:${KAFKA_TOPIC_REPLICA}"
    depends_on:
      - zookeeper

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./${PROMETHEUS_VOLUEM}:/etc/prometheus
    links:
      - kafka

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
