version: "3"

services:
  zookeeper:
    container_name: zookeeper
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - ./zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka:3
    ports:
      - "19092:9092"
    volumes:
      - ./kafka_data:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      # - KAFKA_CFG_LISTENERS=PLAINTEXT://:19092
      # - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:19092
      - KAFKA_INTER_BROKER_USER=ibct
      - KAFKA_INTER_BROKER_PASSWORD=qwer1234
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    # command: sh -c "bin/zookeeper-server-start.sh config/zookeeper.properties & bin/kafka-server-start.sh config/server.properties"

  kafka_exporter:
    container_name: kafka-exporter
    image: danielqsj/kafka-exporter
    command: --kafka.server=129.154.213.183:19092
    ports:
      - "9308:9308"
    depends_on: 
      - kafka

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./${PROMETHEUS_VOLUEM}:/etc/prometheus
    depends_on: 
      - kafka_exporter