version: "3.9"

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./${PROMETHEUS_VOLUEM}:/etc/prometheus